### ISSUE TITLE
Mint with 1tx

### ISSUE THREAD

**Issue by Khoiwall** [booktoshi/Doginals-inscriptions#2]
@booktoshi Hi Bro. Can you mint with 1tx

**Comment by booktoshi** [comment]
Yea

**Comment by Khoiwall** [comment]
@booktoshi Can you help me. Do you use telegram or facebook

**Comment by booktoshi** [comment]
Yea, TG @booktoshi

**Comment by Khoiwall** [comment]
@booktoshi What project use mint with 1Tx

**Comment by fhhg9658** [comment]
hi, I only have the dogecoin node for getblock. Can you help modify it? Can I mint DRC20 using only the getblock node? I am not wealthy, but if you can help me, I would like to pay you a little doge.

**Comment by booktoshi** [comment]
Thats not the way doginals work, did you message me on Telegram? I dont see a message - whats your @ name on telegram?

**Comment by booktoshi** [comment]
Message me on telegram @booktoshi

**Comment by fhhg9658** [comment]
https://chain.so/tx/DOGE/a10e7a2e8525e4b7e5de8a99b7b6d55842401103bfa47b61659fa73373e984d2
hi,How to use this method to mint DRC20.
